### ISSUE TITLE
KeyError: <filter DLT40> in model.py

### ISSUE THREAD

**Issue by jlzhang001** [griffin-h/lightcurve_fitting#8]
When I run CompanionShocking, it shows a KeyError. 
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File /home/lhaaso/jlzhang/TCRB/example_companion.py:103
    100 print(sifto)
    102 lc_early = lc.where(MJD_min=57468., MJD_max=57485.,filter_not=['R','I'])
--> 103 model = CompanionShocking(lc_early)
    104 #model = CompanionShocking2(lc_early)
    105 #model = CompanionShocking3(lc_early)
    106 
    107 # Run the fit
    108 sampler = lightcurve_mcmc(lc_early, model, priors=priors, p_lo=p_lo, p_up=p_up,
    109                           nwalkers=10, nsteps=100, nsteps_burnin=100, show=True)

File ~/software/miniconda3/envs/pipthreeML/lib/python3.8/site-packages/lightcurve_fitting/models.py:714, in BaseCompanionShocking.__init__(self, lc, redshift)
    711         raise Exception('No SiFTO template for filter ' + filt.name)
    713 # assume unfiltered = DLT40 for now
--> 714 self.sifto[unfilt] = self.sifto[dlt40]

KeyError: <filter DLT40>

My scripts in follwoing:
#####CompanionShocking######
from lightcurve_fitting.models import CompanionShocking, CompanionShocking2, CompanionShocking3, UniformPrior
from lightcurve_fitting.fitting import lightcurve_mcmc, lightcurve_corner

# Fit only the early light curve
lc_early = lc.where(MJD_min=57468., MJD_max=57485.)

# Define the priors and initial guesses
priors = [
    UniformPrior(0., 100.),
    UniformPrior(0., 100.),
    UniformPrior(0., 100.),
    UniformPrior(57468., 57468.7),
]
p_lo = [20., 2., 20., 57468.5]
p_up = [50., 5., 50., 57468.7]

lc_early = lc.where(MJD_min=57468., MJD_max=57485.,filter_not=['R','I'])
model = CompanionShocking(lc_early)
# Run the fit
sampler = lightcurve_mcmc(lc_early, model, priors=priors, p_lo=p_lo, p_up=p_up,
                          nwalkers=10, nsteps=100, nsteps_burnin=100, show=True)

# Plot the results
fig, ax_corner, ax_model = lightcurve_corner(lc_early, model, sampler.flatchain)

**Comment by griffin-h** [comment]
Thank you for the bug report! I believe I have fixed this issue in the branch bugfix/sifto_unfilt. Can you try installing the changes and let me know if it solves your problem? You can install the changes with this command:
```
pip install git+https://github.com/griffin-h/lightcurve_fitting.git@bugfix/sifto_unfilt
```

**Comment by jlzhang001** [comment]
Thanks for your reply. 
It seems another error occurs.
I used the the light curve of  SN2016bkv, which is the example in light curve fitting package. There is no filter named 'DLT40'. 

--> 108 model = CompanionShocking3(lc_early)
    110 # Run the fit
    111 sampler = lightcurve_mcmc(lc_early, model, priors=priors, p_lo=p_lo, p_up=p_up,
    112                           nwalkers=18, nsteps=100, nsteps_burnin=100, show=True)

File /sps/grand/jlzhang/miniconda3/envs/p38/envs/fermipy/lib/python3.9/site-packages/lightcurve_fitting/models.py:714, in BaseCompanionShocking.__init__(self, lc, redshift)
    712     scale_filt = filt
    713 else:
--> 714     raise Exception('No SiFTO template for filter ' + filt.name)
    715 lc_filt = lc.where(filter=scale_filt)
    716 sifto_scaled = sifto[sifto_filt] * np.max(lc_filt['lum']) / np.max(sifto[sifto_filt])

Exception: No SiFTO template for filter unfilt.

**Comment by griffin-h** [comment]
This error is expected, because the underlying SN Ia model (SiFTO) used in the CompanionShocking models is only defined in UBVgri. The example light curve of SN 2016bkv included in the package has an unfiltered light curve point from Itagaki that cannot be used for this model. You could exclude that point the same way that you are excluding R and I in this line:
```
lc_early = lc.where(MJD_min=57468., MJD_max=57485., filter_not=['R', 'I', 'unfilt.'])
```
(Of course, keep in mind that SN 2016bkv is a Type II supernova, so it's not appropriate for this model. It's fine for testing.)

**Comment by jlzhang001** [comment]
OK. I understand. It works well!
